---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0

platforms:
    - name: centos-7.2

suites:

  - name: default
    run_list:
      - recipe[dot_env::default]
    attributes:
      dot_env:
        config:
          file1:
            key1: "val1"
            key2: "val2"
        doc_root:
          file1: "/var/www/html/site1"
