name 'dot_env'
maintainer 'Anurag Raperthy'
maintainer_email 'anuragnan@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures dot_env'
long_description 'Installs/Configures dot_env'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/anuragnandan/dot_env/issues'
source_url 'https://github.com/anuragnandan/dot_env'
